<a href="https://colab.research.google.com/github/fonsecajr/Projects/blob/master/A%C3%A7%C3%B5es_Analises6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as nd
import string
import warnings
warnings.filterwarnings('ignore')

In [0]:
url = 'https://www.fundamentus.com.br/resultado.php'
df = pd.read_html(url)

In [3]:
list(df)
type(df)

list

In [4]:
df

[     Papel  Cotação      P/L  ...       Patrim. Líq  Dív.Brut/ Patrim. Cresc. Rec.5a
 0    VNET3      0.0  0.00000  ...   9.257.250.00000                0.0        -2,71%
 1    CFLU4      1.0  0.00000  ...      60.351.00000                6.0         8,14%
 2    CLAN3      0.0  0.00000  ...   1.012.240.00000                0.0       -63,96%
 3    CLSC6      0.0  0.00000  ...   1.551.160.00000                0.0         6,66%
 4    CSTB3  15000.0  0.00000  ...   8.420.670.00000               14.0        31,91%
 ..     ...      ...      ...  ...               ...                ...           ...
 880  CEPE6   2000.0  1.54585  ...   1.667.000.00000              336.0         8,63%
 881  CEPE3   2453.0  1.89599  ...   1.667.000.00000              336.0         8,63%
 882  CEPE5   2511.0  1.94081  ...   1.667.000.00000              336.0         8,63%
 883  BRAP3   3311.0  2.04316  ...  10.522.400.00000                0.0         0,00%
 884  BRAP4   3659.0  2.25790  ...  10.522.400.00000                0.0         0,00%

 [885 rows x 21 columns]]

In [5]:
df[0]

     Papel  Cotação      P/L  ...       Patrim. Líq  Dív.Brut/ Patrim. Cresc. Rec.5a
0    VNET3      0.0  0.00000  ...   9.257.250.00000                0.0        -2,71%
1    CFLU4      1.0  0.00000  ...      60.351.00000                6.0         8,14%
2    CLAN3      0.0  0.00000  ...   1.012.240.00000                0.0       -63,96%
3    CLSC6      0.0  0.00000  ...   1.551.160.00000                0.0         6,66%
4    CSTB3  15000.0  0.00000  ...   8.420.670.00000               14.0        31,91%
..     ...      ...      ...  ...               ...                ...           ...
880  CEPE6   2000.0  1.54585  ...   1.667.000.00000              336.0         8,63%
881  CEPE3   2453.0  1.89599  ...   1.667.000.00000              336.0         8,63%
882  CEPE5   2511.0  1.94081  ...   1.667.000.00000              336.0         8,63%
883  BRAP3   3311.0  2.04316  ...  10.522.400.00000                0.0         0,00%
884  BRAP4   3659.0  2.25790  ...  10.522.400.00000                0.0         0,00%

[885 rows x 21 columns]

In [0]:
df0 = pd.read_html(url, decimal=',', thousands='.')[0]

In [7]:
for coluna in ['Div.Yield', 'Mrg Ebit', 'Mrg. Líq.', 'ROIC', 'Cresc. Rec.5a']:
  df0[coluna] = df0[coluna].str.replace('.', '')
  df0[coluna] = df0[coluna].str.replace(',', '.')
  df0[coluna] = df0[coluna].str.rstrip('%').astype('float') / 100
df0

     Papel  Cotação      P/L  ...   Patrim. Líq  Dív.Brut/ Patrim.  Cresc. Rec.5a
0    VNET3     0.00     0.00  ...  9.257250e+09               0.00        -0.0271
1    CFLU4  1000.00     0.00  ...  6.035100e+07               0.06         0.0814
2    CLAN3     0.00     0.00  ...  1.012240e+09               0.00        -0.6396
3    CLSC6     0.00     0.00  ...  1.551160e+09               0.00         0.0666
4    CSTB3   150.00     0.00  ...  8.420670e+09               0.14         0.3191
..     ...      ...      ...  ...           ...                ...            ...
881  CEPE6    20.00  1545.85  ...  1.667000e+09               3.36         0.0863
882  CEPE3    24.53  1895.99  ...  1.667000e+09               3.36         0.0863
883  CEPE5    25.11  1940.81  ...  1.667000e+09               3.36         0.0863
884  BRAP3    33.11  2043.16  ...  1.052240e+10               0.00         0.0000
885  BRAP4    36.59  2257.90  ...  1.052240e+10               0.00         0.0000

[886 rows x 21 columns]

In [8]:
df0.shape

(886, 21)

In [0]:
dfliquidas = df0[df0['Liq.2meses'] > 1000000]

In [10]:
dfliquidas.shape

(198, 21)

In [0]:
mfa = pd.DataFrame()
mfa['pos'] = range(1, 151)
mfa['EV/EBIT'] = dfliquidas[dfliquidas['EV/EBIT'] > 0].sort_values(by=['EV/EBIT'])['Papel'][:150].values
mfa['ROIC'] = dfliquidas.sort_values(by=['ROIC'], ascending=False)['Papel'][:150].values

In [14]:
magicaformula

     pos EV/EBIT   ROIC
0      1   EMBR3  RCSL4
1      2   PSSA3  WIZS3
2      3   SMLS3  PSSA3
3      4  SULA11  TOTS3
4      5   WIZS3  ODPV3
..   ...     ...    ...
145  146   PNVL3  SUZB3
146  147   GNDI3  JHSF3
147  148   WEGE3  COGN3
148  149   RADL3  LOGG3
149  150   HAPV3  GFSA3

[150 rows x 3 columns]

In [0]:
mfb = magicaformula.pivot_table(columns='EV/EBIT', values='pos')
mfc = magicaformula.pivot_table(columns='ROIC', values='pos')

In [19]:
mfd = pd.concat([mfb,mfc])
mfd

     AALR3  ABEV3  AGRO3  ALPA4  ALSO3  ...  LWSA3  MGLU3  PRNR3  RCSL4  SUZB3
pos  115.0   88.0   89.0  140.0   71.0  ...    NaN    NaN    NaN    NaN    NaN
pos  142.0   15.0   88.0   23.0  130.0  ...  104.0   70.0  145.0    1.0  146.0

[2 rows x 154 columns]

In [24]:
magicaformula = mfd.dropna(axis=1).sum()
magicaformula.sort_values()[:15]

PSSA3      5.0
WIZS3      7.0
SMLS3      9.0
SAPR4     21.0
SAPR11    23.0
LEVE3     27.0
VALE3     29.0
ALUP11    32.0
GOLL4     34.0
AMAR3     41.0
TGMA3     46.0
CVCB3     48.0
TEND3     49.0
BEEF3     50.0
MRFG3     51.0
dtype: float64

**A Fórmula Mágica de Joel Grenblatt.**

Olhe para o “retorno de lucro” (earnings yield) e o “retorno sobre o capital” (return on capital) ao montar sua carteira de investimentos. *(https://www.sunoresearch.com.br/artigos/formula-magica-de-joel-grenblatt-little-book-beats-market/)*

Dispensando as distorções desta função para as empresas financeiras, todas as demais apresentam a barganha, ou seja, empresas que geram mais caixa do que aquele valorizado pela ação no mercado.